CREATE OR REPLACE FUNCTION HAS_STOCK(CID IN NUMBER)
RETURN NUMBER IS
    BID NUMBER;
    AMNT NUMBER;
BEGIN
    FOR R in (SELECT * FROM PICKED WHERE PICKED.CART_ID=CID)
    LOOP
        BID := R.BOOK_ID;
        SELECT STOCK INTO AMNT FROM BOOK WHERE ID = BID;
        IF R.AMOUNT > AMNT THEN
           RETURN 1;
        end if;
    END LOOP;
    RETURN 0;
END;

