-- Insert the star count into book

CREATE OR REPLACE TRIGGER ADD_REVIEW
AFTER INSERT
ON RATES
FOR EACH ROW
DECLARE

BEGIN
    UPDATE BOOK SET STAR = STAR + :NEW.STARS,REVIEW_COUNT = REVIEW_COUNT+1
    WHERE ID = :NEW.BOOK_ID;
end;

-- Update the star count of book

CREATE OR REPLACE TRIGGER UPDATE_REVIEW
AFTER UPDATE
OF STARS
ON RATES
FOR EACH ROW
DECLARE

BEGIN
    UPDATE BOOK SET STAR = STAR + (:NEW.STARS-:OLD.STARS)
    WHERE ID = :NEW.BOOK_ID;
end;

-- change stock after insert
CREATE OR REPLACE TRIGGER UPDATE_STOCK
AFTER INSERT
ON BOOK_ORDER
FOR EACH ROW
DECLARE
    CID NUMBER;
    BID NUMBER;
    AMNT NUMBER;
BEGIN
    CID := :NEW.CART_ID;
    FOR R in (SELECT * FROM PICKED WHERE PICKED.CART_ID=CID)
    LOOP
        BID := R.BOOK_ID;
        AMNT := R.AMOUNT;
        UPDATE BOOK SET STOCK = STOCK - AMNT WHERE ID = BID;
    END LOOP;
END;

